### ISSUE TITLE
Vytvoři footer

### ISSUE THREAD

**Issue by bkarlikova** [antoninkriz/klubfitpp#65]
Bylo by hezké mít na věch stránkách jednotné zápatí s rozcestníkem socek (fb, ig, X,..), button přidej se k nám na dc a adresu (Thákurova 9, Praha 6,  160 00 )

**Comment by Bertik23** [comment]
![image](https://github.com/user-attachments/assets/0461c66b-9dc2-4910-9faa-4b491244edb4)
![image](https://github.com/user-attachments/assets/f6d62ef0-7443-4319-952a-c69007067c44)
Co tohle?

**Comment by bkarlikova** [comment]
Skvělý!

1. prosím doplnit psč ať to vypadá jako real adresa
2. `Přidej se k nám!` bych dala do rámečku s bagroundem - barva klasická oranžová.
3. změnit ikonu twitteru na X

**Comment by Bertik23** [comment]
1. done
2. done
3. ta knihovna co web používá na ikonky nemá ikonku pro X
![image](https://github.com/user-attachments/assets/6b85b825-876c-4089-a3ed-2d9edbfa378a)

**Comment by bkarlikova** [comment]
Top! Za mě to může takhle jít ven.

**Comment by Bertik23** [comment]
Vyřešeno #76
