### ISSUE TITLE
Nejbližší akce

### ISSUE THREAD

**Issue by bkarlikova** [antoninkriz/klubfitpp#68]
V tuhle chvíli jsou všechny akce na jedné stránce. Není vidět co bylo, co bude.

Navrhuju:
- tag u eventů - bude/nebude
- doplnit na hlavní stranu okno nadcházející akce místo akce

**Comment by Bertik23** [comment]
![image](https://github.com/user-attachments/assets/39881962-eae7-4d6a-abd3-1c849d0fe11b)
Při generování stránky to koukne, jestli je akce v budoucnosti a podle toho se zobrazí nebo ne

**Comment by Bertik23** [comment]
Vyřešeno #77
